import { t } from "@/trpc/init";
import { userRouter } from "@/trpc/routers/user.router";
import {
  banksRouter,
  institutionsRouter,
  overviewRouter,
  businessRouter,
} from "@/trpc/routers/core.router";
import { customersRouter } from "@/trpc/routers/customers.router";
import { kycRouter } from "@/trpc/routers/kyc.router";
import { transactionsRouter } from "@/trpc/routers/transactions.router";
import { virtualAccountsRouter } from "@/trpc/routers/virtual-accounts.router";
import { invoicesRouter } from "@/trpc/routers/invoices.router";
import {
  accountingRouter,
  apiKeysRouter,
  appsRouter,
  bankAccountsRouter,
  bankConnectionsRouter,
  bankingRouter,
  billingRouter,
  connectorsRouter,
  documentTagAssignmentsRouter,
  documentTagsRouter,
  documentsRouter,
  inboxAccountsRouter,
  inboxRouter,
  invoicePaymentsRouter,
  invoiceProductsRouter,
  invoiceRecurringRouter,
  invoiceTemplateRouter,
  jobsRouter,
  notificationSettingsRouter,
  notificationsRouter,
  oauthApplicationsRouter,
  reportsRouter,
  searchRouter,
  shortLinksRouter,
  tagsRouter,
  trackerEntriesRouter,
  trackerProjectsRouter,
  transactionAttachmentsRouter,
  transactionCategoriesRouter,
  transactionTagsRouter,
} from "@/trpc/routers/legacy.router";

export const appRouter = t.router({
  user: userRouter,
  business: businessRouter,
  banks: banksRouter,
  transactions: transactionsRouter,
  invoice: invoicesRouter,
  documents: documentsRouter,
  institutions: institutionsRouter,
  overview: overviewRouter,
  notifications: notificationsRouter,
  connectors: connectorsRouter,
  accounting: accountingRouter,
  apiKeys: apiKeysRouter,
  apps: appsRouter,
  bankAccounts: bankAccountsRouter,
  bankConnections: bankConnectionsRouter,
  banking: bankingRouter,
  billing: billingRouter,
  customers: customersRouter,
  kyc: kycRouter,
  virtualAccounts: virtualAccountsRouter,
  documentTagAssignments: documentTagAssignmentsRouter,
  documentTags: documentTagsRouter,
  inbox: inboxRouter,
  inboxAccounts: inboxAccountsRouter,
  invoicePayments: invoicePaymentsRouter,
  invoiceProducts: invoiceProductsRouter,
  invoiceRecurring: invoiceRecurringRouter,
  invoiceTemplate: invoiceTemplateRouter,
  jobs: jobsRouter,
  notificationSettings: notificationSettingsRouter,
  oauthApplications: oauthApplicationsRouter,
  reports: reportsRouter,
  search: searchRouter,
  shortLinks: shortLinksRouter,
  tags: tagsRouter,
  trackerEntries: trackerEntriesRouter,
  trackerProjects: trackerProjectsRouter,
  transactionAttachments: transactionAttachmentsRouter,
  transactionCategories: transactionCategoriesRouter,
  transactionTags: transactionTagsRouter,
});

export type AppRouter = typeof appRouter;
